/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CurriculumSlugRouteImport } from './routes/curriculum.$slug'
import { Route as CurriculumAiAppDevelopmentWithRagAgentsRouteImport } from './routes/curriculum.ai-app-development-with-rag-agents'
import { Route as CurriculumBecomeAnAiEngineerRouteImport } from './routes/curriculum.become-an-ai-engineer'
import { Route as CurriculumFoundationRouteImport } from './routes/curriculum.foundation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumSlugRoute = CurriculumSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CurriculumRoute,
} as any)
const CurriculumAiAppDevelopmentWithRagAgentsRoute =
  CurriculumAiAppDevelopmentWithRagAgentsRouteImport.update({
    id: '/ai-app-development-with-rag-agents',
    path: '/ai-app-development-with-rag-agents',
    getParentRoute: () => CurriculumRoute,
  } as any)
const CurriculumBecomeAnAiEngineerRoute =
  CurriculumBecomeAnAiEngineerRouteImport.update({
    id: '/become-an-ai-engineer',
    path: '/become-an-ai-engineer',
    getParentRoute: () => CurriculumRoute,
  } as any)
const CurriculumFoundationRoute = CurriculumFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => CurriculumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
  '/curriculum/ai-app-development-with-rag-agents': typeof CurriculumAiAppDevelopmentWithRagAgentsRoute
  '/curriculum/become-an-ai-engineer': typeof CurriculumBecomeAnAiEngineerRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
  '/curriculum/ai-app-development-with-rag-agents': typeof CurriculumAiAppDevelopmentWithRagAgentsRoute
  '/curriculum/become-an-ai-engineer': typeof CurriculumBecomeAnAiEngineerRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
  '/curriculum/ai-app-development-with-rag-agents': typeof CurriculumAiAppDevelopmentWithRagAgentsRoute
  '/curriculum/become-an-ai-engineer': typeof CurriculumBecomeAnAiEngineerRoute
  '/curriculum/foundation': typeof CurriculumFoundationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/curriculum'
    | '/curriculum/$slug'
    | '/curriculum/ai-app-development-with-rag-agents'
    | '/curriculum/become-an-ai-engineer'
    | '/curriculum/foundation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/curriculum'
    | '/curriculum/$slug'
    | '/curriculum/ai-app-development-with-rag-agents'
    | '/curriculum/become-an-ai-engineer'
    | '/curriculum/foundation'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/curriculum'
    | '/curriculum/$slug'
    | '/curriculum/ai-app-development-with-rag-agents'
    | '/curriculum/become-an-ai-engineer'
    | '/curriculum/foundation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CurriculumRoute: typeof CurriculumRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$slug': {
      id: '/curriculum/$slug'
      path: '/$slug'
      fullPath: '/curriculum/$slug'
      preLoaderRoute: typeof CurriculumSlugRouteImport
      parentRoute: typeof CurriculumRoute
    }
    '/curriculum/ai-app-development-with-rag-agents': {
      id: '/curriculum/ai-app-development-with-rag-agents'
      path: '/ai-app-development-with-rag-agents'
      fullPath: '/curriculum/ai-app-development-with-rag-agents'
      preLoaderRoute: typeof CurriculumAiAppDevelopmentWithRagAgentsRouteImport
      parentRoute: typeof CurriculumRoute
    }
    '/curriculum/become-an-ai-engineer': {
      id: '/curriculum/become-an-ai-engineer'
      path: '/become-an-ai-engineer'
      fullPath: '/curriculum/become-an-ai-engineer'
      preLoaderRoute: typeof CurriculumBecomeAnAiEngineerRouteImport
      parentRoute: typeof CurriculumRoute
    }
    '/curriculum/foundation': {
      id: '/curriculum/foundation'
      path: '/foundation'
      fullPath: '/curriculum/foundation'
      preLoaderRoute: typeof CurriculumFoundationRouteImport
      parentRoute: typeof CurriculumRoute
    }
  }
}

interface CurriculumRouteChildren {
  CurriculumSlugRoute: typeof CurriculumSlugRoute
  CurriculumAiAppDevelopmentWithRagAgentsRoute: typeof CurriculumAiAppDevelopmentWithRagAgentsRoute
  CurriculumBecomeAnAiEngineerRoute: typeof CurriculumBecomeAnAiEngineerRoute
  CurriculumFoundationRoute: typeof CurriculumFoundationRoute
}

const CurriculumRouteChildren: CurriculumRouteChildren = {
  CurriculumSlugRoute: CurriculumSlugRoute,
  CurriculumAiAppDevelopmentWithRagAgentsRoute:
    CurriculumAiAppDevelopmentWithRagAgentsRoute,
  CurriculumBecomeAnAiEngineerRoute: CurriculumBecomeAnAiEngineerRoute,
  CurriculumFoundationRoute: CurriculumFoundationRoute,
}

const CurriculumRouteWithChildren = CurriculumRoute._addFileChildren(
  CurriculumRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CurriculumRoute: CurriculumRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
