/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CurriculumSlugRouteImport } from './routes/curriculum.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumSlugRoute = CurriculumSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CurriculumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/curriculum': typeof CurriculumRouteWithChildren
  '/curriculum/$slug': typeof CurriculumSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/curriculum' | '/curriculum/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/curriculum' | '/curriculum/$slug'
  id: '__root__' | '/' | '/admin' | '/curriculum' | '/curriculum/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CurriculumRoute: typeof CurriculumRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$slug': {
      id: '/curriculum/$slug'
      path: '/$slug'
      fullPath: '/curriculum/$slug'
      preLoaderRoute: typeof CurriculumSlugRouteImport
      parentRoute: typeof CurriculumRoute
    }
  }
}

interface CurriculumRouteChildren {
  CurriculumSlugRoute: typeof CurriculumSlugRoute
}

const CurriculumRouteChildren: CurriculumRouteChildren = {
  CurriculumSlugRoute: CurriculumSlugRoute,
}

const CurriculumRouteWithChildren = CurriculumRoute._addFileChildren(
  CurriculumRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CurriculumRoute: CurriculumRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
